# 19.0 [Error Handling](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/ErrorHandling.html)

Error handling, is, as the name suggests, the process of handling and responding to errors in your program. Swift has first class support for throwing, catching, propagating, and manipulating recoverable errors at runtime.

## Representing and Throwing Errors

In Swift, errors are represented by values of types that conform to the `Error` protocol. This **empty** protocol indicates that a type can be used for error handling.

Objects of type `enum` are particularly well suited to modeling related error conditions, for instance:

```Swift
enum VendingMachineError: Error {
    case invalidSelection
    case insufficientFunds(coinsNeeded: Int)
    case outOfStock
}
```

Errors are thrown using the `throw` keyword:
```Swift
throw VendingMachineError.insufficientFunds(coinsNeeded: 5)
```

## Handling Errors

When an error thrown, it needs to be dealt with in some way. Swift has 4 ways of dealing with errors. You can:
1. **Propogate Errors using Throwing Functions** - To indicate that a function can throw an error, you mark it with the `throws` keyword:

   ```Swift
   func canThrowErrors() throws -> String
 
   func cannotThrowErrors() -> String
   ```
   
   Such functions propogate errors from inside the function up to the scope in which it was called. That scope can then either itself throw the error, or handle it using one of the following 3 methods.
2. **Handle Errors Using a `do-catch`** - You use a do-catch statement to handle errors by running a block of code. If an error is thrown by the code in the `do` clause, it is matched against the `catch` clauses to determine which one of them can handle the error. The general form of a do-catch statement:
   ```Swift
   do {
    try expressionThatCanThrowAnError
    statements
    } catch errorPattern1 {
        statements
    } catch errorPattern2 where condition {
        statements
    }
   ```

3. **Convert an Error to an Optional Value** - You can use the `try?` keyword to handle an error by converting it into an optional. If the function **does** throw an error, the optional is set to `nil`. Otherwise, the function returns the type it normally would. For example, for the following function:
    ```Swift
    func someThrowingFunction() throws -> Int {
        // ...
    }
    ```
    The two code blocks below have identical behaviour:
    ```Swift
    let x = try? someThrowingFunction()
    ```
    ```Swift
    let x: Int?
    do {
        x = try someThrowingFunction()
    } catch {
        x = nil
    }
    ```

4. **Disable error propogation** - On the other hand, if you are *absolutely certain* that a function will not throw an error at runtime, you can disable error proppogation by writing `try!` before the function:
   ```Swift
   let photo = try! loadImage(atPath: "./Resources/John Appleseed.jpg")
   ```
   Note the if the function does in fact throw an error, you'll get a runtime error.
   
## Specifying Cleanup Actions

There are certain circumstances where you know that you want some code to always be executed just before the current block of code is exited, regardless of how it is exited. An example is opening a file and trying to read from it. Regardless of whether you read successfully or an error is thrown, you will still want to close the file.

Swift allows you to do this using a `defer` block with statements inside it.  The deferred statements may not contain any code that would transfer control out of the statements, such as a break or a return statement, or by throwing an error. Deferred actions are executed in the reverse of the order that theyâ€™re written in your source code. That is, the code in the first defer statement executes last, the code in the second defer statement executes second to last, and so on. The last defer statement in source code order executes first.

```Swift
func processFile(filename: String) throws {
    if exists(filename) {
        let file = open(filename)
        defer {
            close(file)
        }
        while let line = try file.readline() {
            // Work with the file.
        }
        // close(file) is called here, at the end of the scope.
    }
}
```

Note that you can use defer statements even when errors are not involved.

[Previous Section](../18%20-%20Protocols/18.9%20-%20Protocol%20Extensions.md) | [Back To Contents](https://github.com/Firanus/swift-language-guide-notes) | [Next Section](../20%20-%20Type%20Checking/20.0%20-%20Type%20Checking.md)